[package]
name = "actix-simple-http"
version = "0.1.0"
authors = ["bartekus <bartekus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
